version: '3.8'

services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydb
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        command: ['redis-server', '--maxmemory-policy', 'noeviction']
