version: '3.8'
services:
  mydb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
  redis:
    image: redis
    ports:
      - 6379:6379
